services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./symfony:/app # Mount the symfony directory to /app inside the container
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "8000:8000"
    working_dir: /app
    environment:
      - XDEBUG_MODE=debug # to connect to xdebug from phpstorm: File > Settings > PHP > Servers > + >
      # Name: whatever, Host: 127.0.0.1 (localhost can not work), Port: 8000, Debugger: Xdebug,
      # set absolute path on the server for Project_files/(path of the project here)/symfony to /app
    command: symfony server:start --no-interaction --allow-all-ip --no-tls


  node-base:
    container_name: node-base
    image: node:latest
    env_file:
      - ./.env
    volumes:
      - ./frontend/biletron-frontend:/biletron-frontend
    working_dir: /biletron-frontend
    command: bash -c "echo [INFO] This docker service does nothing. It should be extended and not run directly. If you see this message more than one time for the same service, then something is set up incorrectly. This message should be seen only when bare docker compose up is run."

  node-install:
    container_name: node-install
    extends: node-base
    command: npm install
    profiles: [ "install" ]

  node-dev:
    container_name: node-dev
    extends: node-base
    ports:
      - "5173:5173"
    command: npm run dev
    profiles: [ "run-dev" ]
